# Generated by Django 3.1 on 2020-08-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_content', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='writer',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
