# Generated by Django 3.1 on 2020-08-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_content', '0002_news_writer'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='act',
            field=models.IntegerField(default=0),
        ),
    ]
