# Generated by Django 3.1 on 2020-08-30 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('news_content', '0003_news_act'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='picname',
            field=models.ImageField(blank=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
