# Generated by Django 3.1 on 2020-08-29 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0002_remove_manager_ip'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='manager',
            name='country',
        ),
    ]
